# Reference: http://www.appveyor.com/docs/appveyor-yml
# Notes:
#   - Indent each level of configuration with 2 spaces. Do not use tabs!

#---------------------------------#
#      general configuration      #
#---------------------------------#

version: 1.3.1.{build}
image: Visual Studio 2017

clone_folder: C:\Kerbalism
shallow_clone: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

environment:
  smallversion: 1.3.1
  DLL_ARCH_PASS:
    secure: Ae6v2Uf17RNJVGyaHCN24t5aEu5EenMJJwEbx6NiESY=
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-$(configuration)'

#---------------------------------#
#       build configuration       #
#---------------------------------#

configuration:
 - Debug
 - Release
platform: Any CPU
init:
  - git config --global core.autocrlf input
install:
  - cmd: echo Install scripts
  # setup env. variables
  - cmd: echo %APPVEYOR_BUILD_FOLDER%
  - cmd: set KERBALISM_FOLDER=%APPVEYOR_BUILD_FOLDER%\src
  - cmd: dir %KERBALISM_FOLDER%
  - cmd: set ARTIFACTS_FOLDER=%APPVEYOR_BUILD_FOLDER%\artifacts
  - cmd: set GAMEDATA_FOLDER=%APPVEYOR_BUILD_FOLDER%\GameData
  - cmd: set ASSEMBLY_FOLDER=%GAMEDATA_FOLDER%\Kerbalism
  - cmd: set KSPLIB_ARCHIVE_FOLDER=%APPVEYOR_BUILD_FOLDER%\buildscripts\Appveyor
  - cmd: cd %KSPLIB_ARCHIVE_FOLDER% & dir
  - cmd: 7za.exe  e -p'%DLL_ARCH_PASS%' -o'%KERBALISM_FOLDER%' KSPLibraries.7z
  - cmd: echo %KSPLIB_ARCHIVE%
  - cmd: dir %KERBALISM_FOLDER%
build:
  parallel: true
  project: .\Kerbalism.sln
  verbosity: normal
before_package:
    # delete KSP downloaded assembly files
    - cmd: del %KERBALISM_FOLDER%\Assembly-CSharp.dll
    - cmd: del %KERBALISM_FOLDER%\Assembly-CSharp-firstpass.dll
    - cmd: del %KERBALISM_FOLDER%\Assembly-UnityScript.dll
    - cmd: del %KERBALISM_FOLDER%\Assembly-UnityScript-firstpass.dll
    - cmd: del %KERBALISM_FOLDER%\UnityEngine.dll
    - cmd: del %KERBALISM_FOLDER%\UnityEngine.UI.dll
    - cmd: del %KERBALISM_FOLDER%\KSPAssets.dll
    - cmd: cd %KERBALISM_FOLDER% & dir
    - cmd: echo done!
after_build:
    - cmd: xcopy /y %KERBALISM_FOLDER%/obj/Release/Kerbalism.dll %ASSEMBLY_FOLDER%
    - cmd: mkdir %ARTIFACTS_FOLDER%
    - cmd: cd %APPVEYOR_BUILD_FOLDER%
    - cmd: .\buildscripts\ZipPack\7za.exe a %ARTIFACTS_FOLDER%\Kerbalism.zip %GAMEDATA_FOLDER%


#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
 - path: .\artifacts\Kerbalism.zip
   name: Kerbalism-$(appveyor_build_version)-$(configuration)-artifact.zip